//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment_accounting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uchet_evmEntities : DbContext
    {
        public uchet_evmEntities()
            : base("name=uchet_evmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brand { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<main> main { get; set; }
        public virtual DbSet<place> place { get; set; }
        public virtual DbSet<placement> placement { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<type_users> type_users { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<type_equipment> type_equipment { get; set; }
    }
}
